### ISSUE TITLE
Better clear button styling

### ISSUE THREAD

**Issue by bertob** [zoeyfyi/TeX-Match#43]
The "clear" button looks a bit awkward currently, because it touches the borders but it still rounded like a regular button.

I'd recommend adding a 6 or 12px margin all around the button, to make it clearly separate from the edges of the pane. Alternatively you could maybe also move it to the left side of the hearderbar.

![image](https://user-images.githubusercontent.com/1908896/97760820-5da75a80-1b04-11eb-8741-b35450426411.png)

**Comment by zoeyfyi** [comment]
Definitely agree, I forget to check how things look with other themes. https://developer.gnome.org/hig/stable/header-bars.html.en recommends new/back buttons go on the left in the header bar, so I think clear would fit there (its essentially a "new" button). I prefer it over adding a margin, since then its not as clear what space the button occupies and what space is for drawing.
